services:
  inventory-postgres-db:
    image: postgres:12.7 # https://hub.docker.com/_/postgres
    container_name: "inventory-postgres-db"
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=inventory
      - POSTGRES_USER=inventorytest
      - POSTGRES_PASSWORD=local
    restart: 'always'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data